#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


if [ -z "${POSTGRESQL_DB_USER}" ]; then
    base_postgres_image_default_user='postgres'
    export POSTGRESQL_DB_USER="${base_postgres_image_default_user}"
fi

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRESQL_DATABASE}",
        user="${POSTGRESQL_DB_USER}",
        password="${POSTGRESQL_DB_PASS}",
        host="${POSTGRESQL_DB_HOST}",
        port="${POSTGRESQL_DB_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}
until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'

exec "$@"
